const INFO={
 ads:{k:'SERVICE',title:'Ads & Campaign Management',intro:'Performance-led marketplace advertising designed to improve profitable visibility and sales.',items:['Sponsored ads setup & structure','Keyword and search-term strategy','Bid, budget & placement optimization','ROAS / ACOS / TACOS monitoring','Campaign diagnostics & scaling','Weekly performance actions'],note:'Best for brands already selling on marketplaces and looking to improve efficiency or scale.'},
 seo:{k:'SERVICE',title:'Listing & SEO',intro:'Conversion-focused digital shelf optimization so customers can discover and understand your products faster.',items:['Titles, bullets & descriptions','Search keyword mapping','Attributes & catalog hygiene','Competitor and category checks','Conversion-rate improvement','Ongoing listing maintenance'],note:'We optimize content around the platform, category, competition and actual customer intent.'},
 content:{k:'SERVICE',title:'A+ & Brand Content',intro:'Premium brand storytelling that builds trust and helps turn product-page traffic into buyers.',items:['A+ module planning','Comparison sections','Brand story & positioning','Feature-benefit communication','Mobile-first content structure','Seasonal content refresh'],note:'Creative direction is aligned with the product proposition and marketplace buying journey.'},
 creative:{k:'SERVICE',title:'Images & Creatives',intro:'Digital-shelf creative assets built to improve clarity, click-through and conversion.',items:['Main product images','Infographics & feature callouts','Lifestyle creatives','Marketplace banners','Campaign creatives','Creative testing concepts'],note:'Final production requirements depend on platform specifications and the scope agreed for the brand.'},
 store:{k:'SERVICE',title:'Brand Store',intro:'A structured storefront that makes your assortment easier to browse and campaigns easier to merchandise.',items:['Store architecture','Navigation & category hierarchy','Product merchandising','Seasonal/event refreshes','Landing-page experiences','Performance review'],note:'A strong store should connect brand story with commercial intent—not just look attractive.'},
 inventory:{k:'SERVICE',title:'Inventory Management',intro:'Availability-focused operations to reduce lost sales caused by stock-outs and weak replenishment visibility.',items:['Stock visibility','Sell-through tracking','Replenishment planning','Low-stock alerts','Availability analysis','Lost-sales prevention'],note:'Inventory recommendations depend on demand, lead time, MOQ, channel economics and supply constraints.'},
 pogrn:{k:'SERVICE',title:'PO & GRN Management',intro:'Operational coordination to keep purchase orders, receipts and platform supply processes moving.',items:['PO tracking','GRN follow-ups','Supply coordination','Pending-case tracking','Platform escalation support','Status reporting'],note:'We coordinate with relevant stakeholders; physical dispatch and warehouse activities remain with the brand/supply partners.'},
 qcommerce:{k:'SERVICE',title:'Quick-Commerce Growth',intro:'Growth management for fast-commerce channels where assortment, availability and visibility move together.',items:['Assortment planning','Availability monitoring','Visibility opportunities','Promotional strategy','Channel diagnostics','Performance reporting'],note:'Quick-commerce availability and commercial terms vary by city, dark store, category and platform.'},
 meta:{k:'SERVICE',title:'Meta Ads',intro:'Facebook and Instagram performance marketing focused on acquisition, retargeting and scalable creative testing.',items:['Campaign architecture','Audience strategy','Creative testing','Retargeting','Budget optimization','Funnel reporting'],note:'Tracking quality, creative supply, offer strength and landing-page experience materially affect outcomes.'},
 analytics:{k:'SERVICE',title:'Analytics & Reporting',intro:'Action-oriented reporting that explains what changed, why it changed and what should happen next.',items:['Daily/weekly monitoring','Funnel analysis','Campaign diagnostics','SKU-level insights','Performance summaries','Action trackers'],note:'Reporting can be tailored to the KPIs and data access available for each brand.'},
 deals:{k:'SERVICE',title:'Deals & Promotions',intro:'Commercial planning around events, offers and promotions with attention to margin and incremental sales.',items:['Event calendar planning','Offer recommendations','Deal participation support','Promo performance analysis','Incrementality review','Post-event learnings'],note:'Promotion decisions should consider margin, inventory, baseline sales and platform fees—not sales volume alone.'},
 health:{k:'SERVICE',title:'Account Health',intro:'Operational follow-through for listing issues, suppressions, escalations and marketplace account hygiene.',items:['Suppression diagnosis','Issue tracking','Catalog escalations','Case follow-ups','Compliance checks','Operational reporting'],note:'Resolution timelines depend on platform response and the nature of each issue.'},
 amazon:{k:'CHANNEL',title:'Amazon',intro:'Marketplace management across catalog, ads, content, promotions, inventory and account operations.',items:['Catalog & SEO','Sponsored advertising','A+ & Brand Store','Deals & events','Inventory visibility','Account health'],note:'Scope can be focused or full-service depending on your current setup.'},
 flipkart:{k:'CHANNEL',title:'Flipkart',intro:'End-to-end marketplace support across product content, advertising and commercial operations.',items:['Catalog optimization','Ads & visibility','Promotions','Inventory monitoring','Operational follow-up','Reporting'],note:'Channel capabilities and available programs depend on seller/category eligibility.'},
 instamart:{k:'CHANNEL',title:'Instamart',intro:'Quick-commerce growth support focused on assortment, availability, visibility and promotions.',items:['Assortment','Availability','Visibility','Promotions','Performance tracking','Action planning'],note:'City and store-level availability can affect outcomes.'},
 blinkit:{k:'CHANNEL',title:'Blinkit',intro:'Quick-commerce execution for improving discoverability, availability and commercial performance.',items:['Assortment checks','Availability','Visibility planning','Promotions','SKU diagnostics','Reporting'],note:'Execution is aligned to the access and programs available for your account.'},
 zepto:{k:'CHANNEL',title:'Zepto',intro:'Growth support across assortment, availability, visibility and promotional opportunities.',items:['Assortment strategy','Availability monitoring','Visibility','Promotions','SKU analysis','Performance reporting'],note:'Terms and inventory conditions can vary by geography and category.'},
 meesho:{k:'CHANNEL',title:'Meesho',intro:'Marketplace expansion support across catalog quality, ads, offers and operational hygiene.',items:['Catalog optimization','Ads','Offer strategy','Content','Inventory','Account support'],note:'We tailor the playbook to your category, price points and marketplace maturity.'},
 myntra:{k:'CHANNEL',title:'Myntra',intro:'Marketplace support for brands building stronger product presentation and commercial execution.',items:['Catalog support','Content','Promotions','Performance review','Inventory coordination','Operational follow-up'],note:'Scope depends on category and partner access.'},
 d2c:{k:'CHANNEL',title:'D2C',intro:'A connected performance ecosystem across your owned store, paid media, analytics and conversion journey.',items:['Paid acquisition','Creative testing','Conversion optimization','Analytics','Retargeting','Growth planning'],note:'For D2C, tracking, landing-page quality and unit economics are core inputs.'},
 audit:{k:'PROCESS',title:'01 — Audit',intro:'We establish a clear baseline before recommending spend or major changes.',items:['Catalog health','Ads performance','Pricing','Content & conversion','Inventory','Competition & account health'],note:'The audit identifies the highest-impact bottlenecks and quick wins.'},
 strategy:{k:'PROCESS',title:'02 — Strategy',intro:'We turn the audit into a channel-wise roadmap with priorities and measurable actions.',items:['Targets & KPIs','Channel priorities','Budget planning','Content roadmap','Promotion calendar','Execution cadence'],note:'Targets are finalized only after understanding category economics and current performance.'},
 execute:{k:'PROCESS',title:'03 — Execute',intro:'The team moves from recommendations to hands-on implementation.',items:['Listings','Creatives','Campaigns','Promotions','Inventory coordination','Operational follow-ups'],note:'Execution scope is defined by the selected service package and platform access.'},
 optimize:{k:'PROCESS',title:'04 — Optimize',intro:'We continuously learn from performance and redirect effort toward what works.',items:['Measure','Diagnose','Test','Scale winners','Fix bottlenecks','Repeat'],note:'Optimization is an ongoing loop rather than a one-time setup.'}
};
const modal=document.getElementById('infoModal');
function openInfo(key){const x=INFO[key];if(!x)return;document.getElementById('modalKicker').textContent=x.k;document.getElementById('modalTitle').textContent=x.title;document.getElementById('modalIntro').textContent=x.intro;document.getElementById('modalBody').innerHTML='<div class="modal-list">'+x.items.map(i=>'<div>✓ '+i+'</div>').join('')+'</div><div class="modal-note">'+x.note+'</div>';modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeInfo(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}
document.querySelectorAll('.info-card[data-info]').forEach(el=>el.addEventListener('click',()=>openInfo(el.dataset.info)));
document.querySelectorAll('[data-close-modal]').forEach(el=>el.addEventListener('click',closeInfo));
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeInfo()});

document.getElementById('year').textContent=new Date().getFullYear();
const form=document.getElementById('leadForm');
form.addEventListener('submit',async e=>{e.preventDefault();const status=document.getElementById('formStatus');const btn=form.querySelector('button');btn.disabled=true;status.textContent='Sending enquiry…';try{const data=Object.fromEntries(new FormData(form).entries());const r=await fetch('/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const out=await r.json();if(!r.ok)throw new Error(out.message||'Request failed');status.textContent='Thanks — your enquiry has been received. We will follow up shortly.';form.reset()}catch(err){status.textContent='Could not save the enquiry. Please try WhatsApp or call us directly.'}finally{btn.disabled=false}});

const menu=document.querySelector('.menu'),links=document.querySelector('.links');if(menu)menu.addEventListener('click',()=>links.classList.toggle('open'));document.querySelectorAll('.links a').forEach(a=>a.addEventListener('click',()=>links.classList.remove('open')));
